version: '2.4'

############################################################
#
# Troubleshooting:
# GRPC: try using GRPC_VERBOSITY and GRPC_TRACE flags
# More info for GRPC flags: https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
#
# LND: try using DEBUG=trace
# More info on debug levels: https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf
#
############################################################

services:
  lnd_btc:
    image: recover/lnd-btc
    container_name: "recover-lnd-btc"
    ports:
      - '10211:9735'
      - '10212:10009'
    volumes:
      - 'shared:/shared'
      - './data:/data'
      - './backup:/backup'
    build:
      context: docker/lnd
    environment:
      - EXTERNAL_ADDRESS
      - EXTERNAL_PORT=10211
      - RPC_USER
      - RPC_PASS
      - RPC_HOST
      - NETWORK
      - DEBUG=info
      - LND_BASE_FEE=0
      - LND_FEE_RATE=0
    entrypoint: ["./start-lnd.sh"]

volumes:
  shared:
